apiVersion: v1
kind: Service
metadata:
  name: urlshortener
spec:
  selector:
    app: urlshortener
  ports:
    - port: 8080       # Cluster internal port
      targetPort: 8080
      nodePort: 30080  # NodePort for local access
  type: NodePort
