openapi: 3.1.0
info:
  title: URL Shortener API
  description: API for creating and resolving shortened URLs
  version: 1.0.0

servers:
  - url: https://url-shortener.durban.dev
    description: Production
  - url: http://localhost:8080
    description: Local development

tags:
  - name: URL
    description: Operations related to creating and managing short URLs
  - name: Redirect
    description: Operations for redirecting short codes to original URLs

paths:
  /api/v1/urls:
    post:
      tags:
        - URL
      summary: Create a short URL
      description: Generates a short code for a given long URL
      operationId: createShortUrl
      requestBody:
        description: Request payload containing the long URL to be shortened
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShortUrlRequest'
      responses:
        '201':
          description: Short URL created successfully
          headers:
            Location:
              description: The newly created short URL
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateShortUrlResponse'
        '400':
          description: Invalid URL provided
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error while creating a short URL
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

  /{shortCode}:
    get:
      tags:
        - Redirect
      summary: Redirect to long URL
      description: Redirects to the original long URL for the given short code
      operationId: redirectToLongUrl
      parameters:
        - name: shortCode
          in: path
          required: true
          description: The short code identifier
          schema:
            type: string
            minLength: 1
            maxLength: 10
      responses:
        '302':
          description: Redirect to the original URL
          headers:
            Location:
              description: The original long URL
              schema:
                type: string
                format: uri
        '404':
          description: Short code not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Internal server error while redirecting to the original URL
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

components:
  schemas:
    CreateShortUrlRequest:
      type: object
      description: Request body for creating a new shortened URL
      required:
        - longUrl
      properties:
        longUrl:
          type: string
          format: uri
          description: The original long URL that the user wants to shorten
          example: https://example.com/some/very/long/path

    CreateShortUrlResponse:
      type: object
      description: Response returned after successfully creating a short URL
      required:
        - shortCode
        - shortUrl
      properties:
        shortCode:
          type: string
          description: Unique short code generated for the long URL
          example: aZ3kLm
        shortUrl:
          type: string
          format: uri
          description: Fully qualified shortened URL that can be shared
          example: https://short.ly/aZ3kLm

    ProblemDetails:
      type: object
      description: RFC 9457 compliant Problem Details object for HTTP APIs
      required:
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          description: A URI reference that identifies the problem type
          example: "https://short.ly/probs/invalid-url"
        title:
          type: string
          description: Short, human-readable summary of the problem
          example: "Invalid URL"
        status:
          type: integer
          format: int32
          description: HTTP status code generated by the origin server for this occurrence
          example: 400
        detail:
          type: string
          description: Human-readable explanation specific to this occurrence of the problem
          example: "The provided URL is not valid and cannot be shortened."
        instance:
          type: string
          format: uri
          description: A URI reference that identifies the specific occurrence of the problem
          example: "/api/v1/urls/123456789"
